Description:
    model_name: exp2_segmentation_290420241

general: 
    use_deterministic_algorithms: False
    batch_size: 1
    device: 'cuda:0' 
    gpu : 0
    save_path : ./out/example_naturalistic_segmentation
    save_output: [input, stimulation, phosphenes, reconstruction_rgb, label_rgb]
    
simulator:
    base_config: ./_config/exp2/simulator_config.yaml
    phosphene_map: ./_config/phosphene_maps/DefaultCoordinateMap_1000_phosphenes.pickle
    
e2e_models:
    model_architecture: end-to-end-autoencoder # choose from end-to-end-autoencoder, zhao-autoencoder
    in_channels: 3
    n_electrodes: 1000
    output_scaling: 128.0e-6
    output_steps: 10 # output is constrained to 10 possible steps in the range [0, output_scaling]
    out_channels: 250
    encoder_out_activation: sigmoid
    decoder_out_activation: sigmoid

optimization:
    learning_rate : 0.0003535
    epochs : 16
    trainstats_per_epoch : 24
    validations_per_epoch: 8
    early_stop_criterium : 15

training_pipeline:
    pipeline: supervised-segmentation-reconstruction
    regularization_weight: 0.99999  # relative weight for enforcing interpretable (supervised) phosphene encodings
    
dataset:
    dataset: ADE20K # choose from ADE20K, BouncingMNIST
    target: 'segmentation' # choose from 'segmentation', 'boundary'
    num_classes: 250
    data_directory : C:/Users/appel/Documents/Project/Dynaphos/data/michelle123_5658b6fb/ADE20K/
    debug_subset: False # for the ADE50k dataset:
    load_preprocessed: True # for the ADE50k dataset:
    # sequence_length: 5 # for the BouncingMNIST dataset:
    # mode: recon # for the BouncingMNIST dataset: