Description:
    model_name: exp2_boundary_april30

general: 
    use_deterministic_algorithms: False
    batch_size: 2
    device: 'cuda:0' 
    gpu : 0
    save_path : ./out/example_naturalistic_boundary_debug2
    project_name: 'viseon'
    run_name: 'exp2_boundary_april30_debug'
    entity: 'michelleappel'
    model_log_freq: 16
    save_output: [input, stimulation, phosphenes, reconstruction, target]
    
simulator:
    base_config: ./_config/exp2/simulator_config.yaml
    phosphene_map: ./_config/phosphene_maps/DefaultCoordinateMap_1000_phosphenes.pickle
    
e2e_models:
    model_architecture: end-to-end-autoencoder # choose from end-to-end-autoencoder, zhao-autoencoder
    in_channels: 1
    n_electrodes: 1000
    output_scaling: 128.0e-6
    output_steps: 10 # output is constrained to 10 possible steps in the range [0, output_scaling]
    out_channels: 1
    encoder_out_activation: sigmoid
    decoder_out_activation: sigmoid

optimization:
    learning_rate : 0.0003535
    epochs : 1
    trainstats_per_epoch : 24
    validations_per_epoch: 8
    early_stop_criterium : 15

training_pipeline:
    pipeline: supervised-boundary-reconstruction
    regularization_weight: 0.99999  # relative weight for enforcing interpretable (supervised) phosphene encodings
    
dataset:
    dataset: ADE20K # choose from ADE20K, BouncingMNIST
    target: 'boundary' # choose from 'segmentation', 'boundary'
    data_directory : ../data/ADE20K
    load_preprocessed: True # for the ADE50k dataset:
    debug_subset: 100 # for the ADE50k dataset:
    sequence_length: 5 # for the BouncingMNIST dataset:
    mode: recon # for the BouncingMNIST dataset: