Description:
    model_name: exp1_video_nov28

general: 
    use_deterministic_algorithms: False
    batch_size: 2
    device: 'cuda:0' 
    gpu : 0
    save_path : ./Out/Exp1_Nov28
    save_output: ['phosphenes', 'stimulation', 'reconstruction']
    
simulator:
    base_config: ../../config/params.yaml
    use_threshold: False
    phosphene_map: ../../config/DefaultCoordinateMap_1000_phosphenes.pickle
    
e2e_models:
    model_architecture: zhao-autoencoder # choose from end-to-end-autoencoder, zhao-autoencoder
    in_channels: 1
    n_electrodes: 1000
    output_scaling: 128.0e-6
    output_steps: None
    out_channels: 1
    out_activation: sigmoid

optimization:
    learning_rate : 0.0001
    epochs : 45
    trainstats_per_epoch : 60
    validations_per_epoch: 20
    early_stop_criterium : 15

training_pipeline:
    pipeline: unconstrained-video-reconstruction
    regularization_weight: 0.5  # relative weight for enforcing interpretable (supervised) phosphene encodings
    

dataset:
    dataset: BouncingMNIST
    data_directory : ../../../_Datasets/BouncingMnist/
    load_preprocessed: True # for the ADE50k dataset:
    sequence_length: 5 # for the BouncingMNIST dataset:
    mode: recon # for the BouncingMNIST dataset:
    
    


    
    


