Description:
    model_name: faces_no_phosphenes

general: 
    use_deterministic_algorithms: False
    batch_size: 8
    device: 'cuda:0' 
    gpu : 0
    save_path : ./out/faces_supervised/
    project_name: 'viseon'
    run_name: 'face segmentation supervised phosphenes - snellius'
    entity: 'michelleappel'
    model_log_freq: 16
    save_output: [input, stimulation, phosphenes, reconstruction_rgb, label_rgb]
    
simulator:
    base_config: ./_config/exp1/simulator_config.yaml
    phosphene_map: ./_config/phosphene_maps/DefaultCoordinateMap_1000_phosphenes.pickle
    
e2e_models:
    model_architecture: end-to-end-autoencoder # choose from end-to-end-autoencoder, zhao-autoencoder
    in_channels: 3
    n_electrodes: 1000
    output_scaling: 128.0e-6
    output_steps: 10 # output is constrained to 10 possible steps in the range [0, output_scaling]
    out_channels: 11
    encoder_out_activation: sigmoid
    decoder_out_activation: sigmoid

optimization:
    learning_rate: 0.0001
    epochs: 28
    trainstats_per_epoch: 24
    validations_per_epoch: 8
    early_stop_criterium: 15
    alpha: 0.5
    epsilon: 1
    # class_weights: [1.66, 5.34, 359.05, 364.84, 608.89, 607.76, 70.59, 417.37, 407.92, 250.42, 5.6] # with circle mask
    # class_weights: [1.47, 6.8, 457.62, 464.98, 776.2, 774.68, 89.99, 532.09, 520.02, 319.24, 6.76] # without circle mask
    class_weights: [1.45, 6.81, 457.75, 465.14, 776.28, 774.85, 89.99, 532.11, 520.07, 319.26, 7.14] # no circle mask enforced in reconstruction
    weight_decay: 0.000001
    lr_patience: 16
    lr_factor: 0.1
    dice_loss_weight: 0.05
    cross_entropy_loss_weight: 0.05
    regularization_weight: 0.9

training_pipeline:
    pipeline: supervised-segmentation
    regularization_weight: 0  # relative weight for enforcing interpretable (supervised) phosphene encodings
    
dataset:
    dataset: LaPa # choose from ADE20K, BouncingMNIST, LaPa
    target: 'segmentation' # choose from 'segmentation', 'boundary'
    num_classes: 11
    data_directory : ../data/face/LaPa
    debug_subset: False
    circular_mask: True